name: CI

on: [push, pull_request]

jobs:
  sanity-check:
    name: Sanity check
    runs-on: ubuntu-22.04
    container:
      image: "ubuntu:22.04"
    steps:
      - name: Install required dependencies
        run: |
          apt update && apt install --yes sudo
          sudo apt install --yes git
          sudo DEBIAN_FRONTEND=noninteractive apt install --yes npm
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          # needed because of commit-lint, see https://github.com/conventional-changelog/commitlint/issues/3376
          fetch-depth: 0
      # workaround for https://github.com/actions/runner/issues/2033
      - name: ownership workaround
        run: git config --global --add safe.directory '*'
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: ./commitlint.sh --from HEAD~1 --to HEAD --verbose
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: |
          ./commitlint.sh --verbose \
            --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} \
            --to ${{ github.event.pull_request.head.sha }}
      - name: Install dotnet sdk
        run: sudo apt install --yes dotnet6
      - name: Install prettier
        run: npm install prettier@2.8.3
      - name: Check style of our F#, TypeScript and YML code
        run: sudo dotnet fsi scripts/styleChecker.fsx
