name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    container:
      image: "ubuntu:22.04"
    steps:
      - uses: actions/checkout@v2
      - name: Install required dependencies
        run: |
          apt update
          apt install --yes sudo
          sudo apt install --yes --no-install-recommends git
      # workaround for https://github.com/actions/runner/issues/2033
      - name: ownership workaround
        run: git config --global --add safe.directory '*'

      - name: Setup .NET
        run: |
          # We need to install `ca-certificates`, otherwise we get these errors in the CI:
          # Unable to load the service index for source https://api.nuget.org/v3/index.json.
          # The SSL connection could not be established, see inner exception.
          # The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot
          apt install --yes --no-install-recommends ca-certificates

          apt install --yes --no-install-recommends dotnet6

      - name: Compile the conventions solution
        run: dotnet build --configuration Release conventions.sln
      - name: Compile F# scripts
        run: dotnet fsi scripts/compileFSharpScripts.fsx

  file-conventions-tests:
    name: Run FileConventions-lib unit tests
    needs: build
    runs-on: ubuntu-22.04
    container:
      image: "ubuntu:22.04"
    steps:
      - uses: actions/checkout@v2
      - name: Install required dependencies
        run: |
          apt update
          apt install --yes sudo

      - name: Setup .NET
        run: |
          # We need to install `ca-certificates`, otherwise we get these errors in the CI:
          # Unable to load the service index for source https://api.nuget.org/v3/index.json.
          # The SSL connection could not be established, see inner exception.
          # The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot
          apt install --yes --no-install-recommends ca-certificates

          apt install --yes --no-install-recommends dotnet6

      - name: Run tests to validate F# scripts
        run: dotnet test src/FileConventions.Test/FileConventions.Test.fsproj
