name: CI

on: [push, pull_request]

jobs:
  file-conventions-tests:
    name: Run FileConventions-lib unit tests
    needs: build
    runs-on: ubuntu-22.04
    container:
      image: "ubuntu:22.04"
    steps:
      - uses: actions/checkout@v2
      - name: Install required dependencies
        run: |
          apt update
          apt install --yes sudo

          # We need to install curl otherwise we get these errors in the CI:
          # Unable to load the service index for source https://api.nuget.org/v3/index.json.
          # The SSL connection could not be established, see inner exception. 
          # The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot 
          sudo apt install --yes curl

      - name: Setup .NET
        run: apt install -y dotnet6
      - name: Run tests to validate F# scripts
        run: dotnet test src/FileConventions.Test/FileConventions.Test.fsproj
