name: Run unit tests & check conventions

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-22.04
    container:
      image: "ubuntu:22.04"
    steps:
      - uses: actions/checkout@v2
      - name: Install required dependencies
        run: |
          apt update
          apt install -y sudo
          sudo apt install -y git
          sudo DEBIAN_FRONTEND=noninteractive apt install --yes npm
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version
      - name: Create package.json and package-lock.json
        run: |
          npm init --yes
          npm i --package-lock-only
      - name: Install yarn
        run: sudo npm install -g yarn
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version
      - name: pwd
        run: pwd
      - name: ls
        run: ls
      - name: Install jest
        run: |
          sudo npm install --global --save-dev @types/jest
          sudo npm install --global --save-dev jest
      - name: ls
        run: ls
      - name: Run tests to validate our plugins
        run: |
          yarn jest

  sanitycheck:
    runs-on: ubuntu-22.04
    container:
      image: "ubuntu:22.04"
    steps:
      - name: Install required dependencies
        run: |
          apt update && apt install -y sudo
          sudo apt install -y git
          sudo DEBIAN_FRONTEND=noninteractive apt install --yes npm
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          # needed because of commit-lint, see https://github.com/conventional-changelog/commitlint/issues/3376
          fetch-depth: 0
      # workaround for https://github.com/actions/runner/issues/2033
      - name: ownership workaround
        run: git config --global --add safe.directory '*'
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: ./commitlint.sh --from HEAD~1 --to HEAD --verbose
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: ./commitlint.sh --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - name: Install dotnet sdk
        run: sudo apt install -y dotnet6
      - name: Run script to make sure all files end with EOL 
        run: dotnet fsi eofConvention.fsx
