name: CI

on: [push, pull_request]

jobs:
  sanity-check:
    name: Sanity check
    runs-on: ubuntu-22.04
    container:
      image: "ubuntu:22.04"
    steps:
      - name: Install required dependencies
        run: |
          apt update && apt install --yes sudo
          sudo apt install --yes git
          sudo DEBIAN_FRONTEND=noninteractive apt install --yes npm
      - name: Install dotnet sdk
        run: sudo apt install -y dotnet6
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          # needed because of commit-lint, see https://github.com/conventional-changelog/commitlint/issues/3376
          fetch-depth: 0
      # workaround for https://github.com/actions/runner/issues/2033
      - name: ownership workaround
        run: git config --global --add safe.directory '*'
      - name: Check if gitPush1by1 was used
        if: github.event_name == 'pull_request'
        run: dotnet fsi scripts/detectNotUsingGitPush1by1.fsx
      - name: fantomless
        run: |
          dotnet new tool-manifest
          dotnet tool install fantomless-tool --version 4.7.997-prerelease
          dotnet fantomless --recurse .
          git diff --exit-code
