name: CI

on: [push, pull_request]

jobs:
  commitlint-plugins-tests:
    name: Run commitlint-related tests
    runs-on: ubuntu-22.04
    container:
      image: "ubuntu:22.04"
    steps:
      - uses: actions/checkout@v2
      - name: Install required dependencies
        run: |
          apt update
          apt install --yes sudo
          sudo apt install --yes git

          sudo apt install --yes curl
          # can't install ubuntu's default nodejs version because we would get this error:
          # error @jest/core@29.4.1: The engine "node" is incompatible with this module. Expected version "^14.15.0 || ^16.10.0 || >=18.0.0". Got "12.22.9"
          curl --show-error --location https://deb.nodesource.com/setup_14.x | sudo --preserve-env bash -
          sudo DEBIAN_FRONTEND=noninteractive apt install --yes nodejs
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version
      - name: Install yarn
        run: |
          npm install --global yarn
          yarn add --dev jest typescript ts-jest @types/jest
      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version
      - name: Run tests to validate our plugins
        run: yarn jest
