name: Run unit tests & check conventions

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-22.04
    container:
      image: "ubuntu:22.04"
    steps:
      - uses: actions/checkout@v2
      - name: Install required dependencies
        run: |
          apt update
          apt install -y sudo
          sudo apt install -y git
          
          sudo apt install -y curl
          # can't install ubuntu's default nodejs version because we would get this error:
          # error @commitlint/config-conventional@17.1.0: The engine "node" is incompatible with this module. Expected version ">=v14". Got "12.22.9"
          curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo DEBIAN_FRONTEND=noninteractive apt install -y nodejs

      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version
      - name: Install yarn
        run: |
          sudo npm install -g yarn
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version
      - name: Run tests to validate our plugins
        run: yarn jest

  sanitycheck:
    runs-on: ubuntu-22.04
    container:
      image: "ubuntu:22.04"
    steps:
      - name: Install required dependencies
        run: |
          apt update && apt install -y sudo
          sudo apt install -y git
          
          sudo apt install -y curl
          # can't install ubuntu's default nodejs version because we would get this error:
          # error @commitlint/config-conventional@17.1.0: The engine "node" is incompatible with this module. Expected version ">=v14". Got "12.22.9"
          curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo DEBIAN_FRONTEND=noninteractive apt install -y nodejs
          
      - name: Install commitlint dependencies
        run: |
          npm install -g --save commitlint@17.4.0 @commitlint/cli@17.4.0 conventional-changelog-conventionalcommits@5.0.0
          npm i -g --save-dev conventional-changelog-conventionalcommits@5.0.0
          npm install -g @commitlint/config-conventional@17.1.0
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          # needed because of commit-lint, see https://github.com/conventional-changelog/commitlint/issues/3376
          fetch-depth: 0
      # workaround for https://github.com/actions/runner/issues/2033
      - name: ownership workaround
        run: git config --global --add safe.directory '*'
      - name: Install conventions dependencies
        run: |
          sudo npm install
          sudo npm install typescript --save-dev
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version
          tsc --version
      - name: ls node_moduels
        run: ls node_modules
      - name: npm ls
        run: npm ls
      - name: call ls
        run: ls
      - name: call pwd
        run: pwd
      - name: call ls -lha
        run: ls -lha
      - name: use commitlint
        run: |
          echo 'wip' | npx commitlint

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: ./commitlint.sh --from HEAD~1 --to HEAD --verbose
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: ./commitlint.sh --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - name: Install dotnet sdk
        run: sudo apt install -y dotnet6
      - name: Run script to make sure all files end with EOL 
        run: dotnet fsi eofConvention.fsx
