name: CI

on: [push, pull_request]

jobs:
  sanity-check:
    name: Sanity check
    runs-on: ubuntu-22.04
    container:
      image: "ubuntu:22.04"
    steps:
      - name: Install required dependencies
        run: |
          apt update && apt install --yes sudo
          sudo apt install --yes git
          sudo DEBIAN_FRONTEND=noninteractive apt install --yes npm
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          # needed because of commit-lint, see https://github.com/conventional-changelog/commitlint/issues/3376
          fetch-depth: 0
      # workaround for https://github.com/actions/runner/issues/2033
      - name: ownership workaround
        run: git config --system --add safe.directory '*'
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
      - name: Install dotnet sdk
        run: sudo apt install --yes dotnet6
      - name: Install prettier
        run: npm install prettier@2.8.3
      - name: Change file permissions
        # We need this step so we can change the files using `npx prettier --write` in the next step.
        # Otherwise we get permission denied error in the CI.
        run: chmod 777 -R .
      - name: Check style of our F#, TypeScript and YML code
        run: sudo dotnet fsi scripts/styleChecker.fsx
